ROCmSoftwarePlatform/rocRAND

- CONTRIBUTING.md
- README.md
Adding contribution text and build note on gtest
> Adding contribution text and build note on gtest

- CMakeLists.txt
add gfx803 and gfx900 for ROCm 1.9
> add gfx803 and gfx900 for ROCm 1.9

- library/include/rocrand_philox4x32_10.h
Fixed performance drop seen with Philox engine with HIP PR  https://github.com/ROCm-Developer-Tools/HIP/pull/535 - Feature native vector types 
Closes #32
> Fixed performance drop seen with Philox engine with HIP PR 535

- .gitignore
- .gitlab-ci-gputest.yml
- .gitlab-ci.yml
- cmake/Dependencies.cmake
- library/include/hiprand_kernel.h
- library/include/hiprand_kernel_hcc.h
- library/include/rocrand_kernel.h
- library/include/rocrand_philox4x32_10.h
Need to branch for QA testing of rocm-2.1. Are there any concerns with this? I can base of the current master but it may be worth while to include the changes.
> Merging Develop to Master for rocm-2.1 

- CMakeLists.txt
This is being done on just the RC branch. Need to discuss with Anton the long term option for develop.
> Updating version number to reflect rocm release number

- Jenkinsfile
- docker/dockerfile-build-centos
- docker/dockerfile-build-ubuntu-rock
- docker/dockerfile-install-centos
- docker/dockerfile-install-ubuntu
- install
- Adds to CI testing
- Needs to pass CI
> Added hip-clang jobs

- Jenkinsfile
Using makePackage and sudo commands to cut down length of Jenkinsfile
Passed CI
> Refactoring Jenkinsfile, calling makePackage

- .gitlab-ci.yml
- library/CMakeLists.txt
ROCm package names will change to conform to debian standards
> Changing dependency package name

- .gitignore.develop
- .gitlab-ci-gputest.yml
- .gitlab-ci.yml
- README.md
- benchmark/benchmark_curand_kernel.cpp
- benchmark/benchmark_rocrand_kernel.cpp
- cmake/VerifyCompiler.cmake
- docker/dockerfile-build-centos
- docker/dockerfile-build-sles
- docker/dockerfile-build-ubuntu-rock
- library/CMakeLists.txt
- library/include/hiprand.h
- library/include/rocrand.h
- library/include/rocrand_mtgp32_11213.h
- library/src/rng/mrg32k3a.hpp
- library/src/rng/mtgp32.hpp
- library/src/rng/philox4x32_10.hpp
- library/src/rng/sobol32.hpp
- library/src/rng/xorwow.hpp
- test/package/CMakeLists.txt
- test/test_hiprand_kernel.cpp
- test/test_rocrand_kernel_mrg32k3a.cpp
- test/test_rocrand_kernel_mtgp32.cpp
- test/test_rocrand_kernel_philox4x32_10.cpp
- test/test_rocrand_kernel_sobol32.cpp
- test/test_rocrand_kernel_xorwow.cpp
- test/test_rocrand_mrg32k3a_prng.cpp
> Launch bounds

- benchmark/benchmark_curand_kernel.cpp
- benchmark/benchmark_rocrand_kernel.cpp
- library/include/hiprand.h
- library/include/rocrand.h
- library/src/rng/mrg32k3a.hpp
- library/src/rng/mtgp32.hpp
- library/src/rng/philox4x32_10.hpp
- library/src/rng/sobol32.hpp
- library/src/rng/xorwow.hpp
- test/test_rocrand_kernel_mtgp32.cpp
The internal review findings came later.
> Rename variable to *DEFAULT_MAX_BLOCK_SIZE

- .gitlab-ci-gputest.yml
- .gitlab-ci.yml
- .jenkins/precheckin.groovy
- CMakeLists.txt
- README.md
- library/include/rocrand_common.h
- test/package/CMakeLists.txt
-Disable injecting inline assembly
-Plus small CI changes.
-Readme update with link.
> Mad u64 u32 only pre gfx1030

- CMakeLists.txt
- cmake/Dependencies.cmake
- test/test_hiprand_cpp_wrapper.cpp
- test/test_hiprand_kernel.cpp
- test/test_poisson_distribution.cpp
- test/test_rocrand_basic.cpp
- test/test_rocrand_cpp_wrapper.cpp
- test/test_rocrand_generate.cpp
- test/test_rocrand_generate_log_normal.cpp
- test/test_rocrand_generate_normal.cpp
- test/test_rocrand_generate_poisson.cpp
- test/test_rocrand_generate_uniform.cpp
- test/test_rocrand_kernel_mrg32k3a.cpp
- test/test_rocrand_kernel_mtgp32.cpp
- test/test_rocrand_kernel_philox4x32_10.cpp
- test/test_rocrand_kernel_sobol32.cpp
- test/test_rocrand_kernel_xorwow.cpp
Also removing deprecated warnings from unit tests; updated googletest to 1.10
> Adding xnack flags

- .gitlab-ci.yml
- library/include/rocrand_common.h
Reenable Mad u64 u32 on gfx8-9
> Reenable Mad u64 u32 on gfx8-9

- .jenkins/precheckin.groovy
- .jenkins/staticlibrary.groovy
Needed for rocALUTION which has rocrand as dependency
> Add centos8 to CI

- .jenkins/precheckin.groovy
- .jenkins/staticlibrary.groovy
- CHANGELOG.md
- CMakeLists.txt
Also includes targetid changes.
> Update for ROCm 4.0

- CMakeLists.txt
> Add gfx803 to AMDGPU_TARGETS

- .gitlab-ci.yml
- CMakeLists.txt
- benchmark/CMakeLists.txt
- benchmark/benchmark_rocrand_generate.cpp
- benchmark/benchmark_rocrand_kernel.cpp
- cmake/Dependencies.cmake
- cmake/SetupNVCC.cmake
- cmake/VerifyCompiler.cmake
- library/CMakeLists.txt
- python/hiprand/hiprand/hip.py
- python/rocrand/rocrand/hip.py
- test/CMakeLists.txt
- test/linkage/CMakeLists.txt
Reverts ROCmSoftwarePlatform/rocRAND#173
This is changing how hipRAND is packaged. I am reverting this PR immediately.
> Revert "Develop stream 20210414"

- .gitlab-ci.yml
- CMakeLists.txt
- benchmark/CMakeLists.txt
- benchmark/benchmark_rocrand_generate.cpp
- benchmark/benchmark_rocrand_kernel.cpp
- cmake/Dependencies.cmake
- cmake/SetupNVCC.cmake
- cmake/VerifyCompiler.cmake
- library/CMakeLists.txt
- python/hiprand/hiprand/hip.py
- python/rocrand/rocrand/hip.py
- test/CMakeLists.txt
- test/linkage/CMakeLists.txt
* Revert revert-173-develop_stream_20210414 without rocm-cmake
* Update gitlab CI
> Develop stream 20210601

- library/include/rocrand_log_normal.h
- library/include/rocrand_normal.h
- library/include/rocrand_uniform.h
> Fix order of state next calls

- CMakeLists.txt
Set path used for packaging on Linux if not previously set
> set packaging path if not set on Linux

- .gitlab-ci.yml
- tools/sobol32_direction_vector_generator.cpp
- tools/sobol64_direction_vector_generator.cpp
* Remove references
* Update gitlab CI
> Develop stream 2021 11 29

- library/CMakeLists.txt
* Setup the license file
* fix hipRAND commit
> Hotfix: Hotfixes from ROCm 5.0 that weren't merged

- rmake.py
* avoids use of env var. ROCM_PATH for other purpose
> avoids req. ROCM_PATH env var

- CHANGELOG.md
Hello,
I think I found a typo in the CHANGELOG. Please correct me if I'm wrong.
> Fix typo in the CHANGELOG

- toolchain-windows.cmake
Do not merge until PM approval given.
> Fix toolchain-windows.cmake for HIP SDK (#313)

- CHANGELOG.md
- benchmark/CMakeLists.txt
- benchmark/benchmark_rocrand_kernel.cpp
- cmake/Dependencies.cmake
- rmake.py
- toolchain-windows.cmake
Do not merge until PM approval given.
> 5.5 cherry pick

- benchmark/benchmark_rocrand_kernel.cpp
- library/include/rocrand/rocrand_discrete.h
@RobsonRLemos rebased onto 5.7 staging
Work done by @ex-rzr
> Benchmark perf. improvements for discrete distrubutions

- benchmark/benchmark_rocrand_kernel.cpp
- library/include/rocrand/rocrand_discrete.h
This 5.7 cherry pick address benchmark performance improvements for discrete distributions
> 5.7 cherry pick - Benchmark perf. improvements for discrete distributions
