- library/CMakeLists.txt
When building with top of 1.8.x branches of HIP and HCC, there is a build issues with missing gridlaunch.h header file. hip::hip_hcc no longer has a dependency on HCC runtime, so we need to use hip::device now.
> Fix missing gridlaunch.h build issue

- test/crush/stat_test_common.hpp
Comment from swdev-155298
FE generates invalid addrspace_cast from constant to generic, which then leads to ill-formed Phi.
> fix for swdev-155298

- library/include/hiprand_kernel.h
- library/include/hiprand_kernel_hcc.h
- library/include/rocrand_kernel.h
This PR is equivalent to #34 and addresses the reviewer comment. The original commits are unchanged.
Since hip_hcc is defining `__foreceinline__` [here](https://github.com/ROCm-Developer-Tools/HIP/blob/bd658aa9ea249068eb5034d9a8f157567f57fed8/include/hip/hcc_detail/host_defines.h#L55) which includes the attribute `inline` the additional usage of the inline attribute within rocRAND creates warnings.
warning with `rocm 2.0.89 amd64`
```
/opt/rocm/rocrand/include/rocrand_normal.h:179:1: warning: duplicate 'inline' declaration specifier [-Wduplicate-decl-specifier]
FQUALIFIERS
^
/opt/rocm/hiprand/include/hiprand_kernel_hcc.h:35:21: note: expanded from macro 'FQUALIFIERS'
^
/opt/rocm/hiprand/include/hiprand_kernel.h:26:31: note: expanded from macro 'QUALIFIERS'
#define QUALIFIERS inline …
```
> warning: duplicate 'inline' declaration specifier

- library/include/hiprand_kernel.h
- library/include/rocrand_kernel.h
As of HIP PR #654, `__forceinline__` is defined compatible with CUDA.
> unify forceinline/inline handling

- library/include/rocrand_philox4x32_10.h
Clang native vector types support indexing, and HIP vector types expose a `::data` member which represents the underlying native vector, so we might as well use it.
> Simplify convoluted vector indexing

- test/crush/stat_test_common.hpp
- Need to include <functinoal> explicitly.
- Need to replace `__attribute__((cpu))` with `__host__`.
> Fix hip-clang compilation error.

- .gitlab-ci.yml
Error was:
```
File "/tmp/pip-build-lNW8PJ/numpy/setup.py", line 31, in <module>
raise RuntimeError("Python version >= 3.5 required.")
RuntimeError: Python version >= 3.5 required.
----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lNW8PJ/numpy/
You are using pip version 8.1.1, however version 19.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ERROR: Job failed: exit code 1
```
This fixes it
> Fixing pip version error

- cmake/Common.cmake
When upgrading to newer version of Rocrand RPM library,
pre uninstall script of old library will delete the symlinks
created by the post installation scripts.
This is the sequence of steps followed for RPM package upgrade.
pre install ; install; post install ; pre uninstall ;
uninstall; post uninstall
Add logic in pre uninstall script to check if its uninstall or
upgrade.
Add new script for pre installation. If its upgrade, then this script will
remove symlinks.
For Debian packages, these changes will not have ay effect since uninstall scripts
are called before calling the installation scripts.
> Rocrand build: Fix Update method

- cmake/Common.cmake
- install
- New mode of building is added "-r,--relocatable" which is used
for ROCm stack installed in /opt/rocm-ver.
- Below CMAKE parameters are set/overwritten in above mode
CMAKE_INSTALL_PREFIX
CMAKE_PREFIX_PATH
CMAKE_SHARED_LINKER_FLAGS
CMAKE_MODULE_PATH
ROCM_DISABLE_LDCONFIG
Signed-off-by: Pruthvi Madugundu <mpruthvi@gmail.com>
> rocRAND changes to support multiple ROCM installation

- .gitlab-ci.yml
- cmake/VerifyCompiler.cmake
- test/package/CMakeLists.txt
Set the hip compiler to nvcc, at incorrect case.
Important part:
```
if((HIP_COMPILER STREQUAL "hcc") AND (HIP_PLATFORM STREQUAL "nvcc"))
set(HIP_COMPILER "nvcc" CACHE STRING "HIP Compiler" FORCE)
endif()
```
> Hip compiler for nvcc

- library/CMakeLists.txt
- Git commit number is removed
- ROCM_VERSION number will be appended to component version as ...<rocm_version_number>
only when defined in the ENV.
- CPACK_DEBIAN_PACKAGE_RELEASE and CPACK_RPM_PACKAGE_RELEASE are set to git hash,
if not defined in the ENV which will be defined in the CI environment to provide all the build info.
> Updates to the package name to support ROCm upgrade

- library/CMakeLists.txt
The code changes handle the case when rocRAND_VERSION_TWEAK variable is not defined,
(set by the rocm_setup_version() API), happens when GIT TAG is not available in the repo.
> Handling the GIT TAG null case for package file name

- .jenkins/staticanalysis.groovy
- python/hiprand/docs/Makefile
- python/rocrand/docs/Makefile
This adds a Jenkins build for the docs. I'm not entirely sure the best way to handle having both the rocrand and hiprand docs in the same repository, but both are getting built and tested even if only one is actually viewable on the Jenkins page.
> Add Jenkins docs build

- library/include/rocrand_xorwow.h
The workaround restores lost performance for xorwow engine in newer ROCm builds.  This affected both MI50/Vega20 and MI100.
I'll file an internal ticket with the HIP compiler team shortly about these regressions.
> Workaround performance fix for xorwow

- library/include/hiprand.hpp
- library/include/rocrand.hpp
- test/test_poisson_distribution.cpp
Fix memory leaks in rocRAND:
* test_poisson_distribution: the test requires an explicit deallocation because we test an internal implementation here (the code that uses rocRAND/hipRAND cannot cause the leak because `rocrand_destroy_discrete_distribution` deallocates memory).
* test_rocrand_cpp_wrapper and test_hiprand_cpp_wrapper: wrappers need to destroy rocrand/hiprand generators when the generator has been created correctly but setting seed/offset/dimensions throws an exception (the tests check such cases).
> Fix memory leaks in rocRAND

- cmake/Dependencies.cmake
Currently in https://github.com/ROCmSoftwarePlatform/rocRAND/blob/develop/cmake/Dependencies.cmake#L73:
We call find_package in config mode and pass our local GTest install dir GTEST_ROOT as a hint via the PATHS argument.  I assume that if we're force installing GTest locally, then we want to find our local installed package first versus anything installed in system directories (ie /usr/local/lib).  
However, according to find_package documentation https://cmake.org/cmake/help/latest/command/find_package.html#full-signature-and-config-mode it looks in the cache entry <PackageName>_DIR first before anything we pass in PATHS.  If there is already a preexisting GTest install in system directories, <PackageName>_DIR seems to point to that first instead of GTEST_ROOT.  This most likely will …
> Fix for find_package() after GTest force install 

- library/CMakeLists.txt
Use `rocm_export_targets` for the export file installation instead of doing so manually. This ensures the package prefix directory is correctly set.
> Fix configuration files

- install
Install script will download hipRAND if
- it is trying to build hipRAND (which it is by default), and
- hipRAND/CMakeLists.txt does not exist.
> Change install script hipRAND download behaviour

- CHANGELOG.md
- install
- library/CMakeLists.txt
Create symlinks in the old rocrand header file locations for compatibility.
> Hotfix: symlinks for compatibility

- test/test_rocrand_kernel_xorwow.cpp
For some reason having __launch_bounds__(64) is causing hangs or memory access fault or incorrect results on MI200 and HIP on Windows gfx1030.  Until we figure out why, I am temporarily removing it from affected test cases.
> Temporarily disabling launch_bounds for xorwow unit test

- library/include/rocrand/rocrand_mrg32k3a.h
- library/include/rocrand/rocrand_mtgp32.h
- library/include/rocrand/rocrand_philox4x32_10.h
- library/include/rocrand/rocrand_sobol32.h
- library/include/rocrand/rocrand_sobol64.h
- library/include/rocrand/rocrand_xorwow.h
- test/test_rocrand_kernel_mrg32k3a.cpp
- test/test_rocrand_kernel_mtgp32.cpp
- test/test_rocrand_kernel_philox4x32_10.cpp
- test/test_rocrand_kernel_sobol32.cpp
- test/test_rocrand_kernel_sobol64.cpp
- test/test_rocrand_kernel_xorwow.cpp
Defining destructors prevents the RNG states from being trivially copyable or destructible, which I believe makes it technically undefined behavior to assign using memcpy/hipMemcpy. Regardless, the destructor can interfere with safety checks to ensure that data being transferred to device is trivially copyable.
This issue was discovered during the recent Crusher hackathon while porting [Celeritas](https://github.com/celeritas-project/celeritas) to use HIP.
> Remove trivial but explicit destructors

- rtest.xml
I've filed an internal ticket with the compiler team.  Until it is resolved, we should disable the test to get CI passing again.
> Temporarily disabling xorwow unit test for HIP on Windows due to compiler bug

- library/include/rocrand/rocrand_common.h
This reverts enabling inline assembly for gfx90a and gfx1030, which
was introduced as workaround for a compiler bug since fixed.
Enabling inline assembly negatively affects the performance for these
architectures in some cases.
> Revert enabling inline assembly from #239

- benchmark/CMakeLists.txt
- benchmark/cmdparser.hpp
- library/CMakeLists.txt
- rmake.py
- test/CMakeLists.txt
1. Copying necessary DLLs for benchmarks and unit tests (install (TARGETS rocrand DESTINATION "${PROJECT_BINARY_DIR}/test") does not seem to work)
2. Add required function overload in Windows
> Fixing benchmark and unit test build for Windows

- CHANGELOG.md
This is an autogenerated PR.
This is intended to pull any hotfixes for ROCm release 5.2.0 (including changelogs and documentation) back into develop.
> Hotfixes from release/rocm-rel-5.2 at release 5.2.0

- CHANGELOG.md
- benchmark/benchmark_rocrand_generate.cpp
When running the generate benchmark on Navi21 with select distributions + engine types, we get data that fits in the L3 cache, generating artificially high benchmark scores vs. running the entire benchmark suite, which can lead to a source of confusion for end users.  As @Maetveis suggested, increasing the number of warmup iterations will stop this phenomenon from happening.
> Benchmark warmup increase

- library/include/rocrand/rocrand_common.h
QA performance testing revealed that enable inline assembly actually benefits navi21 in the rocRAND philox benchmarks (the previous assessment of inline asm being bad for MI200 is still correct though).
rocrand-kernel/philox-poisson: 14.25% loss without inline asm
rocrand-kernel/philox-discrete-custom: 5.89% loss
rocrand-kernel/philox-discrete-poisson: 5.52% loss
rocrand-generate/philox-poisson: 7.68% loss
> Re-enable inline asm for gfx1030

- cmake/Dependencies.cmake
As per my comments in https://github.com/ROCmSoftwarePlatform/rocRAND/pull/277.
> Fixes to enable googlebenchmark build on Windows

- CHANGELOG.md
- library/include/rocrand/rocrand_log_normal.h
- library/include/rocrand/rocrand_normal.h
- library/include/rocrand/rocrand_uniform.h
- library/src/rng/distribution/log_normal.hpp
- library/src/rng/scrambled_sobol32.hpp
- library/src/rng/scrambled_sobol64.hpp
- library/src/rng/sobol32.hpp
- library/src/rng/sobol64.hpp
- python/rocrand/tests/rocrand_test.py
- test/test_log_normal_distribution.cpp
- test/test_rocrand_kernel_scrambled_sobol64.cpp
- test/test_rocrand_scrambled_sobol64_qrng.cpp
- Revert fix for Sobol64 distributions due to disproportionally large impact on performance. Temporarily disable tests that expose this pre-existing problem.
- Change `exp` to `expf` for `float` types.
- Fix unnecessary change to `sobol_log_normal_distribution` interface.
> Revert Sobol64 distributions

- CHANGELOG.md
- library/include/rocrand/rocrand_normal.h
- library/include/rocrand/rocrand_uniform.h
- python/rocrand/tests/rocrand_test.py
- test/test_rocrand_kernel_scrambled_sobol64.cpp
- test/test_rocrand_scrambled_sobol64_qrng.cpp
#289 reverts a fix to the 64-bits distributions for Sobol64, due to unexpected performance regressions. After review, this turns out to be the correct approach, the bug made the earlier achieved performance possible.
> Re-enable Sobol64 distributions

- CHANGELOG.md
- library/include/rocrand/rocrand_threefry2_impl.h
- library/include/rocrand/rocrand_threefry4_impl.h
Corrects the array indexing for the Threefry4x32 and Threefry4x64 generators. This bug caused incorrect sequences to be produced by these two generators.
> Fix Threefry4x32 and Threefry4x64 array indexing

- cmake/Dependencies.cmake
- rmake.py
- toolchain-windows.cmake
Previously we did not account for spaces in the HIP installation path in Windows (ie. C:\Program Files, etc).
> HIP SDK compatibility

- .jenkins/codecov.groovy
- .jenkins/common.groovy
- CMakeLists.txt
- README.md
- codecov.yml
This PR does the following:
- adds a `CODE_COVERAGE` flag to the cmake file, which will build with code coverage enabled if building with clang
- adds a codecov jenkins job which will build with the `CODE_COVERAGE` flag on, run the unit tests, collect the coverage results, and upload them to codecov.
- This will track coverage on master and codecov will post a comment on each PR with the impact that the PR has on code coverage.
- adds a codecov.yml file to set options for codecov.
- adds the codecov coverage badge to the main readme.
> Add CodeCov Integration

- library/include/rocrand/rocrand_common.h
The `-fvisibility=hidden` flag does not affect kernels and thus all `__global__` GPU functions become externally-visible symbols by default. Marking them as static will hide them.
This is not strictly necessary, since the rocrand kernels are all appropriately confined to the rocrand details namespace. However, it is still useful to hide their symbols, as it is difficult to review ABI changes between different versions of rocrand when the output of dpkg-gensymbols is full of kernels that change from release to release.
> Hide symbols for GPU kernels

- cmake/Dependencies.cmake
The rocRAND project might use Git to download dependencies, but it is not required if the dependencies are already installed. And, even in the case that Git is needed to download dependencies, this find_package call remains unnecessary. The tooling that does the downloads will look for git itself.
This is the same change as #273, as it was reverted by #300.
> Remove build dependency on Git

- library/include/rocrand/rocrand_common.h
This 5.6 Cherry Pick fix inline assembly so that the it is disable for MI200.
> 5.6 cherry pick - fix inline assembly

- library/CMakeLists.txt
- library/include/rocrand/rocrandapi.h
On Windows, the default compiler behaviour is to hide symbols and exported symbols must be marked explicitly as being exported. On Linux, the default compiler behaviour is to make all symbols visible by default. The default can be changed by setting the `CXX_VISIBILITY_PRESET` CMake property on the library to add `-fvisibility=hidden` to the compiler options. This makes Linux work like Windows in that only the symbols explicitly marked for export are publicly visible.
When only symbols intended to be part of the public ABI are visible, it makes it much easier to review changes, because it means that any removal is a breaking change (whereas currently you need to check if the removal corresponds to a function declared in the public headers to know).
> Hide library internal symbols

- tools/scrambled_sobol32_direction_vector_generator.cpp
- tools/scrambled_sobol64_direction_vector_generator.cpp
- tools/sobol32_direction_vector_generator.cpp
- tools/sobol64_direction_vector_generator.cpp
Reference: https://gcc.gnu.org/gcc-13/porting_to.html
> sobol64_direction_vector_generator.cpp: include stdint.h for uint*_t

- .github/CODEOWNERS
- .github/CODEOWNERS~
Adding code owners for documentation. Plan is to add mandatory reviews from this group of code owners to merge any documentation changes. 
The header directory is related to documentation and thus changes to that are also flagged for documentation review.
> Add Codeowners for Documentation

- benchmark/benchmark_rocrand_kernel.cpp
- library/include/rocrand/rocrand_discrete.h
* Enable gfx94x build targets (#353)
---------
* 5.7 cherry pick - Benchmark perf. improvements for discrete distributions (#379)
* Remove workaround with hipGridDim_x * hipBlockDim_x
It makes no difference anymore on ROCm >= 5.5, probably after switching to code object v5.
* Use restrict with tables of discrete distributions
This change improves performance in device API benchamrks for most engines.
---------
---------
> cherry pick hot fixes from 5.7
